moved tags to last

diff --git a/.github/workflows/eks-deploy-v2.yml b/.github/workflows/eks-deploy-v2.yml
--- a/.github/workflows/eks-deploy-v2.yml
+++ b/.github/workflows/eks-deploy-v2.yml
@@ -84,49 +84,8 @@ jobs:
           aws-region: us-east-1
           role-to-assume: ${{ inputs.github_oidc_role }}
 
-      - name: Tag ECR image with environment
-        run: |
-        
-          set -e
-      
-          # This form of token is needed for the ECR API
-          AUTH_TOKEN=$(aws ecr get-authorization-token --output text --query 'authorizationData[].authorizationToken')
-      
-          # Set registry and repository details
-          REGISTRY_NAME="https://${{ inputs.aws_account_id_ecr }}.dkr.ecr.us-east-1.amazonaws.com"
-          TAG="${{ inputs.image_version }}"
-          ENVIRONMENT_TAG="${{ inputs.environment }}"
-          CONTENT_TYPE="application/vnd.docker.distribution.manifest.v2+json"
-
-          if [[ "${{ inputs.service_name }}" == "littera-core-api" ]]; then
-            REPOSITORY="littera-core"
-          else
-            REPOSITORY="${{ inputs.service_name }}"
-          fi
-
-          # Fetch the manifest of the existing image
-          MANIFEST=$(curl -s -H "Authorization: Basic $AUTH_TOKEN" -H "Accept: $CONTENT_TYPE" "$REGISTRY_NAME/v2/$REPOSITORY/manifests/$TAG")
-      
-          # Check for curl failure
-          if [ $? -ne 0 ]; then
-            echo "Failed to fetch the manifest for tag $TAG."
-            exit 1
-          fi
-
-          echo MANIFEST: $MANIFEST
-      
-          # Push the fetched manifest as a new tag
-          RESPONSE_CODE=$(curl -s -o /dev/null -w "%{http_code}" -X PUT -H "Authorization: Basic $AUTH_TOKEN" -H "Content-Type: $CONTENT_TYPE" -d "$MANIFEST" "$REGISTRY_NAME/v2/$REPOSITORY/manifests/$ENVIRONMENT_TAG")
-          
-          # Check if the image retagging was successful
-          if [ "$RESPONSE_CODE" != "201" ]; then
-            echo "Failed to tag image, server responded with status code $RESPONSE_CODE."
-            exit 1
-          fi
-          echo "Image $TAG tagged $ENVIRONMENT_TAG."
-
       - name: Checkout EKS Config Repo/'develop' branch
-        if: ${{ inputs.cluster_name == 'littera-eks-dev3' || inputs.cluster_name == 'littera-eks-staging3' || inputs.cluster_name == 'littera-eks-production3' }}
+        if: inputs.cluster_name == 'littera-eks-dev3' || inputs.cluster_name == 'littera-eks-staging3' || inputs.cluster_name == 'littera-eks-production3'
         uses: actions/checkout@v4
         with:
           repository: Littera-Education/littera-eks-config
@@ -136,7 +95,7 @@ jobs:
           fetch-depth: 0
 
       - name: Checkout EKS Config Repo/'community_mod' branch
-        if: ${{ inputs.cluster_name == 'littera-eks-dev4' || inputs.cluster_name == 'littera-eks-staging4' || inputs.cluster_name == 'littera-eks-production4' }}
+        if: inputs.cluster_name == 'littera-eks-dev4' || inputs.cluster_name == 'littera-eks-staging4' || inputs.cluster_name == 'littera-eks-production4'
         uses: actions/checkout@v4
         with:
           repository: Littera-Education/littera-eks-config
@@ -146,9 +105,8 @@ jobs:
           fetch-depth: 0
 
       - name: Apply Deployment and ConfigMap
-        if: ${{ inputs.cluster_name == 'littera-eks-dev3' || inputs.cluster_name == 'littera-eks-staging3' || inputs.cluster_name == 'littera-eks-production3' }}
+        if: inputs.cluster_name == 'littera-eks-dev3' || inputs.cluster_name == 'littera-eks-staging3' || inputs.cluster_name == 'littera-eks-production3'
         run: |
-
           set -e
 
           # install kubectl
@@ -205,20 +163,15 @@ jobs:
           fi
 
       - name: Install yq
-        if: ${{ inputs.cluster_name == 'littera-eks-dev4' || inputs.cluster_name == 'littera-eks-staging4' || inputs.cluster_name == 'littera-eks-production4' }}
+        if: inputs.cluster_name == 'littera-eks-dev4' || inputs.cluster_name == 'littera-eks-staging4' || inputs.cluster_name == 'littera-eks-production4'
         env:
           YQ_VERSION: v4.27.2
         run: |
           sudo wget https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64 -O /usr/bin/yq
           sudo chmod +x /usr/bin/yq
-
-      # - uses: azure/setup-kubectl@v3
-      #   if: ${{ inputs.cluster_name == 'littera-eks-dev4' || inputs.cluster_name == 'littera-eks-staging4' || inputs.cluster_name == 'littera-eks-production4' }}
-      #   with:
-      #     version: '1.29.4'
   
       - name: Patch Deployment and Apply ConfigMap
-        if: ${{ inputs.cluster_name == 'littera-eks-dev4' || inputs.cluster_name == 'littera-eks-staging4' || inputs.cluster_name == 'littera-eks-production4' }}
+        if: inputs.cluster_name == 'littera-eks-dev4' || inputs.cluster_name == 'littera-eks-staging4' || inputs.cluster_name == 'littera-eks-production4'
         env:
           service_name: ${{ inputs.service_name }}
           image_version: ${{ inputs.image_version }}
@@ -229,8 +182,8 @@ jobs:
           no_change_substring: "unchanged (server dry run)"
           kubctl_download_url: ${{ inputs.kubctl_download_url }}
           cluster_name: ${{ inputs.cluster_name }}
+          github_actions_deploy_timeout: ${{ inputs.github_actions_deploy_timeout }}
         run: |
-  
           set -e
 
           # install kubectl
@@ -279,6 +232,15 @@ jobs:
               echo configmap_restart: "$configmap_restart"
           fi
 
+          echo
+          echo ***************************************************************************************************
+          echo 
+          echo NOTE: If the action fails due to the timeout of $github_actions_deploy_timeout}
+          echo the deployment may still have succeeded. Please contact devops in #team-devops-collab about this
+          echo 
+          echo ***************************************************************************************************
+          echo
+
           if [[ $deployment_restart == true ]] ; then
               echo "deployment will initiate a rolling restart"
               kubectl apply -f configmaps.yaml
@@ -301,3 +263,43 @@ jobs:
                   kubectl rollout status deployment $service_name -n littera-services-$environment
               fi
           fi
+      
+      - name: Tag ECR image with environment
+        run: |
+          set -e
+
+          # This form of token is needed for the ECR API
+          AUTH_TOKEN=$(aws ecr get-authorization-token --output text --query 'authorizationData[].authorizationToken')
+
+          # Set registry and repository details
+          REGISTRY_NAME="https://${{ inputs.aws_account_id_ecr }}.dkr.ecr.us-east-1.amazonaws.com"
+          TAG="${{ inputs.image_version }}"
+          ENVIRONMENT_TAG="${{ inputs.environment }}"
+          CONTENT_TYPE="application/vnd.docker.distribution.manifest.v2+json"
+
+          if [[ "${{ inputs.service_name }}" == "littera-core-api" ]]; then
+            REPOSITORY="littera-core"
+          else
+            REPOSITORY="${{ inputs.service_name }}"
+          fi
+
+          # Fetch the manifest of the existing image
+          MANIFEST=$(curl -s -H "Authorization: Basic $AUTH_TOKEN" -H "Accept: $CONTENT_TYPE" "$REGISTRY_NAME/v2/$REPOSITORY/manifests/$TAG")
+
+          # Check for curl failure
+          if [ $? -ne 0 ]; then
+            echo "Failed to fetch the manifest for tag $TAG."
+            exit 1
+          fi
+
+          echo MANIFEST: $MANIFEST
+
+          # Push the fetched manifest as a new tag
+          RESPONSE_CODE=$(curl -s -o /dev/null -w "%{http_code}" -X PUT -H "Authorization: Basic $AUTH_TOKEN" -H "Content-Type: $CONTENT_TYPE" -d "$MANIFEST" "$REGISTRY_NAME/v2/$REPOSITORY/manifests/$ENVIRONMENT_TAG")
+          
+          # Check if the image retagging was successful
+          if [ "$RESPONSE_CODE" != "201" ]; then
+            echo "Failed to tag image, server responded with status code $RESPONSE_CODE."
+            exit 1
+          fi
+          echo "Image $TAG tagged $ENVIRONMENT_TAG."
