testing evaluating to true regardless of exit code

diff --git a/.github/workflows/eks-deploy-v2.yml b/.github/workflows/eks-deploy-v2.yml
--- a/.github/workflows/eks-deploy-v2.yml
+++ b/.github/workflows/eks-deploy-v2.yml
@@ -97,11 +97,13 @@ jobs:
             kubectl rollout restart deployment littera-core-worker -n littera-services-${{ inputs.environment }}
           else
             kubectl rollout restart deployment ${{ inputs.service_name }} -n littera-services-${{ inputs.environment }}
-            kubectl rollout status deployment ${{ inputs.service_name }} -n littera-services-${{ inputs.environment }} --timeout=${{ inputs.github_actions_deploy_timeout }} || true
-            if [[ $? -ne 0 ]]; then
-               echo "Timeout reached. However, deployment hasn't necessarily failed. Please reach out to devops."
-               exit 0
-            else
-               echo "Deployed successfully"
-            fi
+            kubectl rollout status deployment ${{ inputs.service_name }} -n littera-services-${{ inputs.environment }} --timeout=${{ inputs.github_actions_deploy_timeout }} || true |
+            while IFS= read -r line
+            do
+              if [[ $line == "error: timed out waiting for the condition" ]]; then
+                echo "Timeout reached. However, deployment hasn't necessarily failed. Please reach out to devops."
+              else
+                echo "Deployed successfully"
+              fi
+            done
           fi
