replacing sonar scanner dnd with bash

diff --git a/.github/workflows/npm-test.yml b/.github/workflows/npm-test.yml
--- a/.github/workflows/npm-test.yml
+++ b/.github/workflows/npm-test.yml
@@ -107,11 +107,33 @@ jobs:
       - name: Check linting
         run: npm run lint
 
+      # - name: SonarQube Scan
+      #   uses: sonarsource/sonarqube-scan-action@v2
+      #   continue-on-error: true
+      #   with:
+      #     args: >
+      #       -Dsonar.projectVersion=${{ steps.get-project-info.outputs.VERSION }}
+      #   env:
+      #     SONAR_TOKEN: ${{ secrets.sonar_token }}
+      #     SONAR_HOST_URL: 'https://sonarcloud.io'
+
+      - name: Install SonarScanner
+        run: npm install -g sonar-scanner
+  
       - name: SonarQube Scan
-        uses: sonarsource/sonarqube-scan-action@v2
-        with:
-          args: >
-            -Dsonar.projectVersion=${{ steps.get-project-info.outputs.VERSION }}
-        env:
-          SONAR_TOKEN: ${{ secrets.sonar_token }}
-          SONAR_HOST_URL: 'https://sonarcloud.io'
+        run: |
+          sonar-scanner \
+            -Dsonar.projectVersion=${{ steps.get-project-info.outputs.VERSION }} \
+            -Dsonar.projectKey=my-nodejs-project \
+            -Dsonar.sources=. \
+            -Dsonar.host.url=https://sonarcloud.io \
+            -Dsonar.login=${{ secrets.sonar_token }}
+
+          # status=$?
+
+          # if [ $status -eq 1 ]; then
+          #   echo "SonarQube scan failed with exit code 1. Continuing the workflow..."
+          # elif [ $status -ne 0 ]; then
+          #   echo "SonarQube scan failed with an unexpected exit code ($status). Stopping the workflow."
+          #   exit 1
+          # fi
